### ISSUE TITLE
Invalid shape error during prefix tuning ByT5

### ISSUE THREAD

**Issue by namednil** [adapter-hub/adapters#553]
## Environment info

     
- `adapter-transformers` version: 3.2.1
- Platform: Linux
- Python version: 3.10.10
- PyTorch version (GPU?): 2.0.0+cpu
- Tensorflow version (GPU?): N/A
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

## Information

Model I am using (Bert, XLNet ...): ByT5

Adapter setup I am using (if any): Prefix Tuning

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

## To reproduce

```python
import transformers

model = transformers.AutoModelForSeq2SeqLM.from_pretrained("google/byt5-small")
tok = transformers.AutoTokenizer.from_pretrained("google/byt5-small")

model.add_adapter("my_adapter", "prefix_tuning", set_active=True)

model(**tok(["input text", "input text 2"], text_target=["output", "output 2"], return_tensors="pt", padding=True))
```
throws the following exception
```
Traceback (most recent call last):
  File "/home/matthias/phd/artificial_tasks/preft.py", line 8, in <module>
    model(**tok(["input text", "input text 2"], text_target=["output", "output 2"], return_tensors="pt", padding=True))
  File "/home/matthias/miniconda3/envs/meta_adapters/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/matthias/miniconda3/envs/meta_adapters/lib/python3.10/site-packages/transformers/adapters/context.py", line 104, in wrapper_func
    with cls(self, *args, **kwargs) as ctx:
  File "/home/matthias/miniconda3/envs/meta_adapters/lib/python3.10/site-packages/transformers/adapters/context.py", line 86, in __init__
    model.forward_context(self, *args, **kwargs)
  File "/home/matthias/miniconda3/envs/meta_adapters/lib/python3.10/site-packages/transformers/adapters/model_mixin.py", line 871, in forward_context
    context.prefix_states = self.base_model.prefix_tuning(*args, **kwargs)
  File "/home/matthias/miniconda3/envs/meta_adapters/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/matthias/miniconda3/envs/meta_adapters/lib/python3.10/site-packages/transformers/adapters/prefix_tuning.py", line 220, in forward
    prefix_states[name] = self.prefix_tunings[name](batch_size)
  File "/home/matthias/miniconda3/envs/meta_adapters/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/matthias/miniconda3/envs/meta_adapters/lib/python3.10/site-packages/transformers/adapters/prefix_tuning.py", line 117, in forward
    return {k: v(batch_size) for k, v in self.items()}
  File "/home/matthias/miniconda3/envs/meta_adapters/lib/python3.10/site-packages/transformers/adapters/prefix_tuning.py", line 117, in <dictcomp>
    return {k: v(batch_size) for k, v in self.items()}
  File "/home/matthias/miniconda3/envs/meta_adapters/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/matthias/miniconda3/envs/meta_adapters/lib/python3.10/site-packages/transformers/adapters/prefix_tuning.py", line 54, in forward
    key_values = key_values.view(
RuntimeError: shape '[2, 30, 24, 6, 245]' is invalid for input of size 2119680
```
I suspect this happens because the number of layers in the encoder and the decoder are not the same for ByT5 unlike most transformer models.

**Comment by calpt** [comment]
This should be fixed since the [release of the new `adapters` package](https://adapterhub.ml/blog/2023/11/introducing-adapters/), succeesind `adapter-transformers`. Please re-open if the issue still persists.
